name: IVR v2 Main

on:
  push:
    paths:
      - 'IVRv2/**'
  pull_request:
    paths:
      - 'IVRv2/**'

jobs:
  test:
    uses: ./.github/workflows/IVRv2/test.yml
  
  deploy-to-docker:
    needs: test
    if: github.ref == 'refs/heads/a4i/main' && github.event_name == 'push'
    uses: ./.github/workflows/IVRv2/deploy-docker.yml
    secrets: inherit
    
  deploy-to-render:
    needs: deploy-to-docker
    if: github.ref == 'refs/heads/a4i/main' && github.event_name == 'push' && (vars.DEPLOYMENT_TARGET == 'render' || vars.DEPLOYMENT_TARGET == 'both' || vars.DEPLOYMENT_TARGET == '' || vars.DEPLOYMENT_TARGET == null)
    uses: ./.github/workflows/IVRv2/deploy-render.yml
    secrets: inherit
    with:
      service_name: ivr-v2

  deploy-to-azure:
    needs: deploy-to-docker
    if: github.ref == 'refs/heads/a4i/main' && github.event_name == 'push' && (vars.DEPLOYMENT_TARGET == 'azure' || vars.DEPLOYMENT_TARGET == 'both')
    uses: ./.github/workflows/IVRv2/deploy-azure.yml
    secrets: inherit
    with:
      service_name: ivr-v2
