name: Run Python Lint
description: Run ruff linter for a Python project
inputs:
  directory:
    description: "Directory of the Python project"
    required: true
runs:
  using: composite
  steps:
    - name: Lint with ruff
      shell: bash
      run: |
        cd ${{ inputs.directory }}
        poetry run ruff check .
