services:
  - type: web
    name: contentwebapp
    rootDir: ContentWebApp
    runtime: docker
    envVars:
      - key: REACT_APP_API_BASE_URL
        sync: false
      - key: REACT_APP_FIREBASEAPIKEY
        sync: false
      - key: REACT_APP_FIREBASEAUTHDOMAIN
        sync: false
      - key: REACT_APP_FIREBASEPROJECTID
        sync: false
      - key: REACT_APP_FIREBASESTORAGEBUCKET
        sync: false
      - key: REACT_APP_FIREBASEMESSAGINGSENDERID
        sync: false
      - key: REACT_APP_FIREBASEAPPID
        sync: false
      - key: REACT_APP_FIREBASEMEASUREMENTID
        sync: false
      