default_platform(:android)

platform :android do
  desc "Build and deploy a staging version to Firebase App Distribution"
  lane :deploy_staging do
    UI.message("Running unit tests...")

    # gradle(
    #   task: 'testDebugUnitTest'
    # )
    
    gradle(
      task: 'assembleDebug',
      properties: {
        "BASE_URL" => ENV['BASE_URL'],
        "CONTENT_URL" => ENV['CONTENT_URL']
        "TENANT_NAME" => ENV['TENANT_NAME']
      }
    )

    firebase_app_distribution(
      app: ENV['FIREBASE_APP_ID'],

      apk_path: "app/build/outputs/apk/debug/app-debug.apk",

      groups: ENV['FIREBASE_TESTER_GROUPS'],

      firebase_cli_token: ENV['FIREBASE_CLI_TOKEN'],

      release_notes: "New staging build uploaded by fastlane."
    )

    UI.success("Successfully built and deployed to Firebase App Distribution!")
  end

  desc "Build and deploy a production version to Firebase App Distribution"
  lane :deploy_prod do
    UI.message("Running unit tests...")

    # gradle(
    #   task: 'testReleaseUnitTest'
    # )
    
    gradle(
      task: 'assembleRelease',
      properties: {
        "BASE_URL" => ENV['PROD_BASE_URL'],
        "CONTENT_URL" => ENV['PROD_CONTENT_URL']
        "TENANT_NAME" => ENV['FIREBASE_PROD_TESTER_GROUPS']
      }
    )

    firebase_app_distribution(
      app: ENV['FIREBASE_PROD_APP_ID'],

      apk_path: "app/build/outputs/apk/release/app-release.apk",

      groups: ENV['FIREBASE_PROD_TESTER_GROUPS'],

      firebase_cli_token: ENV['FIREBASE_CLI_TOKEN'],

      release_notes: "New production build uploaded by fastlane."
    )

    UI.success("Successfully built and deployed to Firebase App Distribution!")
  end
end