export const APP_CONFIG = {
  BASE_URL: process.env.REACT_APP_API_BASE_URL,
  CONF_SERVER_BASE_URI: process.env.REACT_APP_CONF_SERVER_BASE_URI,
  STORAGE_ACCOUNT_NAME: process.env.REACT_APP_STORAGE_ACCOUNT_NAME,
};
