import { defaultSchema } from "rehype-sanitize";

const MATHML_TAGS = [
  "math",
  "maction",
  "maligngroup",
  "malignmark",
  "menclose",
  "merror",
  "mfenced",
  "mfrac",
  "mglyph",
  "mi",
  "mlabeledtr",
  "mlongdiv",
  "mmultiscripts",
  "mn",
  "mo",
  "mover",
  "mpadded",
  "mphantom",
  "mprescripts",
  "mroot",
  "mrow",
  "ms",
  "mscarries",
  "mscarry",
  "msgroup",
  "msline",
  "mspace",
  "msqrt",
  "msrow",
  "mstack",
  "mstyle",
  "msub",
  "msubsup",
  "msup",
  "mtable",
  "mtd",
  "mtext",
  "mtr",
  "munder",
  "munderover",
  "none",
  "semantics",
  "annotation",
];

const MATHML_ATTRIBUTES = [
  "xmlns",
  "display",
  "className",
  "mathvariant",
  "mathsize",
  "mathcolor",
  "mathbackground",
  "stretchy",
  "fence",
  "separator",
  "form",
  "largeop",
  "movablelimits",
  "accent",
  "accentunder",
  "lspace",
  "rspace",
  "minsize",
  "maxsize",
  "encoding",
  "definitionURL",
  "columnalign",
  "rowalign",
  "columnspacing",
  "rowspacing",
  "columnlines",
  "rowlines",
  "frame",
  "framespacing",
  "equalrows",
  "equalcolumns",
  "notation",
  "width",
  "height",
];

export const remediationSanitizeSchema = {
  ...defaultSchema,
  tagNames: [...defaultSchema.tagNames, ...MATHML_TAGS],
  attributes: {
    ...defaultSchema.attributes,
    img: [...defaultSchema.attributes.img, "width", "height"],
    code: [["className", /^language-./, "math-display", "math-inline"]],
    ...Object.fromEntries(MATHML_TAGS.map((tag) => [tag, MATHML_ATTRIBUTES])),
  },
};
