name: Content Web App Main

on:
  push:
    branches: [ a4i/main ]
    paths:
      - 'ContentWebApp/**'
  pull_request:
    branches: [ a4i/main ]
    paths:
      - 'ContentWebApp/**'

jobs:
  test:
    uses: ./.github/workflows/ContentWebApp/test.yml
  
  deploy-to-docker:
    needs: test
    if: github.ref == 'refs/heads/a4i/main' 
    uses: ./.github/workflows/ContentWebApp/deploy-docker.yml
    secrets: inherit

  deploy-to-render:
    needs: deploy-to-docker
    if: github.ref == 'refs/heads/a4i/main'  && (vars.DEPLOYMENT_TARGET == 'render' || vars.DEPLOYMENT_TARGET == 'both' || vars.DEPLOYMENT_TARGET == '' || vars.DEPLOYMENT_TARGET == null)
    uses: ./.github/workflows/ContentWebApp/deploy-render.yml
    secrets: inherit
    with:
      service_name: content-webapp

  deploy-to-azure:
    needs: deploy-to-docker
    if: github.ref == 'refs/heads/a4i/main'  && (vars.DEPLOYMENT_TARGET == 'azure' || vars.DEPLOYMENT_TARGET == 'both')
    uses: ./.github/workflows/ContentWebApp/deploy-azure.yml
    secrets: inherit
    with:
      service_name: content-webapp
