name: Deploy Android Staging Build

# Triggers the workflow on push events to the staging branch
on:
  push:
    branches: [a4i/main, a4i/staging, 'teacher-app-ci']
  pull_request:
    branches: [a4i/main, a4i/staging, 'teacher-app-ci']
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true 
      - name: Create .env file for Fastlane and Gradle
        run: |
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> fastlane/.env
          echo "CONTENT_URL=${{ secrets.CONTENT_URL }}" >> fastlane/.env
          echo "FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}" >> fastlane/.env
          echo "FIREBASE_TESTER_GROUPS=${{ secrets.FIREBASE_TESTER_GROUPS }}" >> fastlane/.env
          echo "FIREBASE_CLI_TOKEN=${{ secrets.FIREBASE_CLI_TOKEN }}" >> fastlane/.env
        
      # Run the Fastlane deployment lane
      - name: Build and Deploy with Fastlane
        if: github.ref == 'refs/heads/a4i/main'
        run: bundle exec fastlane deploy_staging