name: Deploy Services

on:
  push:
    branches: [a4i/main, a4i/staging]
  pull_request:
    branches: [a4i/main, a4i/staging]
  workflow_call:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  service:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: backend-server
            context: backend-server
            image: backend-server
            lang: node
            render_deploy_hook_url: BACKEND_SERVER_RENDER_DEPLOY_HOOK_URL
            azure_publish_profile: BACKEND_SERVER_AZURE_PUBLISH_PROFILE

          - name: content-webapp
            context: ContentWebApp
            image: content-webapp
            lang: node
            render_deploy_hook_url: CONTENT_WEBAPP_RENDER_DEPLOY_HOOK_URL
            azure_publish_profile: CONTENT_WEBAPP_AZURE_PUBLISH_PROFILE

          - name: teacher-webapp
            context: teacher-webapp
            image: teacher-webapp
            lang: node
            render_deploy_hook_url: TEACHER_WEBAPP_RENDER_DEPLOY_HOOK_URL
            azure_publish_profile: TEACHER_WEBAPP_AZURE_PUBLISH_PROFILE

          - name: websocket-service
            context: websocket-service
            image: websocket-service
            lang: node
            render_deploy_hook_url: WEBSOCKET_RENDER_DEPLOY_HOOK_URL
            azure_publish_profile: WEBSOCKET_SERVICE_AZURE_PUBLISH_PROFILE

          - name: conference-v2
            context: ConferenceV2
            image: conference-v2
            lang: python
            render_deploy_hook_url: CONFERENCE_V2_RENDER_DEPLOY_HOOK_URL
            azure_publish_profile: CONFERENCE_V2_AZURE_PUBLISH_PROFILE

          - name: IvrV2
            context: IVRv2
            image: ivrv2
            lang: python
            render_deploy_hook_url: IVRV2_RENDER_DEPLOY_HOOK_URL
            azure_publish_profile: IVRV2_AZURE_PUBLISH_PROFILE
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up language (Poetry)
        if: matrix.service.lang == 'python'
        uses: ./.github/actions/setup-poetry
        with:
          python-version: "3.12"
          directory: ${{ matrix.service.context }}

      - name: Set up language (Node.js)
        if: matrix.service.lang == 'node'
        uses: ./.github/actions/setup-node
        with:
          node-version: "20"
          directory: ${{ matrix.service.context }}

      - name: Run tests (python)
        if: matrix.service.lang == 'python'
        uses: ./.github/actions/run-python-tests
        with:
          directory: ${{ matrix.service.context }}

      - name: Run tests (Node.js)
        if: matrix.service.lang == 'node'
        uses: ./.github/actions/run-node-tests
        with:
          directory: ${{ matrix.service.context }}

      - name: Extract coverage (python)
        if: matrix.service.lang == 'python'
        uses: ./.github/actions/extract-coverage-python
        with:
          coverage_gist_token: ${{ secrets.COVERAGE_GIST_TOKEN }}
          coverage_gist_id: ${{ vars.COVERAGE_GIST_ID }}
          directory: ${{ matrix.service.context }}

      - name: Extract coverage (Node.js)
        if: matrix.service.lang == 'node'
        uses: ./.github/actions/extract-coverage-node
        with:
          coverage_gist_token: ${{ secrets.COVERAGE_GIST_TOKEN }}
          coverage_gist_id: ${{ vars.COVERAGE_GIST_ID }}
          directory: ${{ matrix.service.context }}

      - name: Determine environment tag
        id: env-tag
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/a4i/main" ]]; then
            echo "tag=prod" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == "refs/heads/a4i/staging" ]]; then
            echo "tag=staging" >> $GITHUB_OUTPUT
          else
            echo "tag=latest" >> $GITHUB_OUTPUT
          fi

      - name: Build & push image
        uses: ./.github/actions/deploy-docker
        with:
          context: ${{ matrix.service.context }}
          image: ${{ matrix.service.image }}
          registry: ${{ env.REGISTRY }}
          repository: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          username: ${{ github.actor }}
          environment_tag: ${{ steps.env-tag.outputs.tag }}

      - name: Deploy to Render
        if: github.event_name == 'push' && github.ref == 'refs/heads/a4i/staging'
        uses: ./.github/actions/deploy-render
        with:
          deploy_hook_url: ${{ secrets[ matrix.service.render_deploy_hook_url ] }}

      - name: Deploy to Azure
        if: github.event_name == 'push' && github.ref == 'refs/heads/a4i/main'
        uses: ./.github/actions/deploy-azure
        with:
          app_name: ${{ matrix.service.name }}
          publish_profile: ${{ secrets[matrix.service.azure_publish_profile] }}
          image: ${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.service.image }}:${{ steps.env-tag.outputs.tag }}
