name: Deploy Websocket Service Main

on:
  push:
    branches: a4i/main
  workflow_call:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build & push image
        uses: ./.github/actions/deploy-docker
        with:
          context: websocket-service
          image: websocket-service
          registry: ${{ env.REGISTRY }}
          repository: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          username: ${{ github.actor }}
          environment_tag: prod

      - name: Normalize repo name to lowercase
        id: repo
        run: echo "repository_lowercase=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT

      - name: Deploy to Azure
        uses: ./.github/actions/deploy-azure
        with:
          app_name: web-socket-service-main
          publish_profile: ${{ secrets.WEBSOCKET_SERVICE_AZURE_PUBLISH_PROFILE }}
          image: ${{ env.REGISTRY }}/${{ steps.repo.outputs.repository_lowercase }}/websocket-service:prod
