name: Execute Workflows

on:
  push:
    branches: [a4i/main, a4i/staging,teams-alert]
  workflow_dispatch:

jobs:

  deploy-websocket-service-main-workflow:
    if: github.ref == 'refs/heads/a4i/main'
    uses: ./.github/workflows/deploy-websocket-service-main.yml
    secrets: inherit

  deploy-websocket-service-staging-workflow:
    if: github.ref == 'refs/heads/a4i/staging'
    uses: ./.github/workflows/deploy-websocket-service-staging.yml
    secrets: inherit

  deploy-staging-workflow:
    if: github.ref == 'refs/heads/a4i/staging'
    uses: ./.github/workflows/deploy-staging.yml
    secrets: inherit

  deploy-main-workflow:
    if: github.ref == 'refs/heads/a4i/main'
    uses: ./.github/workflows/deploy-main.yml
    secrets: inherit

  deploy-android:
    if: github.ref == 'refs/heads/a4i/staging' || github.ref == 'refs/heads/a4i/main'
    uses: ./.github/workflows/android-deploy.yml
    secrets: inherit

  run-coverage-summary:
    needs: deploy-staging-workflow
    uses: ./.github/workflows/coverage-summary.yml
    secrets: inherit

  notify-teams:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - deploy-websocket-service-main-workflow
      - deploy-websocket-service-staging-workflow
      - deploy-staging-workflow
      - deploy-main-workflow
      - deploy-android
      - run-coverage-summary
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate Notification Facts
        id: facts
        shell: bash
        run: |
          facts_list=()

          add_fact() {
            local name="$1"
            local value="$2"
            facts_list+=("{ \"name\": \"$name\", \"value\": \"$value\" }")
          }

          add_fact "Workflow" "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

          # Calculate overall status
          if [[ "${{ contains(needs.*.result, 'failure') }}" == "true" ]]; then
            add_fact "Stage" "Workflow Failed"
          else
            add_fact "Stage" "Workflow Complete"
          fi

          if [[ "${{ needs.deploy-websocket-service-main-workflow.result }}" != "skipped" ]]; then
            add_fact "Websocket Main" "${{ needs.deploy-websocket-service-main-workflow.result }}"
          fi

          if [[ "${{ needs.deploy-websocket-service-staging-workflow.result }}" != "skipped" ]]; then
            add_fact "Websocket Staging" "${{ needs.deploy-websocket-service-staging-workflow.result }}"
          fi

          if [[ "${{ needs.deploy-staging-workflow.result }}" != "skipped" ]]; then
            add_fact "Webservice Staging" "${{ needs.deploy-staging-workflow.result }}"
          fi

          if [[ "${{ needs.deploy-main-workflow.result }}" != "skipped" ]]; then
            add_fact "Webservice Main" "${{ needs.deploy-main-workflow.result }}"
          fi

          if [[ "${{ needs.deploy-android.result }}" != "skipped" ]]; then
            add_fact "Android Staging" "${{ needs.deploy-android.result }}"
          fi

          IFS=,
          json_string="[${facts_list[*]}]"

          echo "facts_json<<EOF" >> $GITHUB_OUTPUT
          echo "$json_string" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
