name: Execute backend-server-main

on:
    push:
        branches: [ main ]
    workflow_dispatch:

jobs:
    run-backend-workflow:
        uses: ./.github/workflows/backend-server-main.yml
        secrets: inherit